### ISSUE TITLE
How to understand that the session has expired?

### ISSUE THREAD

**Issue by klepov** [WalletConnect/WalletConnectFlutterV2#150]
Hello! Thanks for this great library!

I call .getActiveSessions() - the library shows the active session, but in trust wallet i killed the session. 
It turns out that the library stores the local session in sp, but this session is killed in trust wallet

is there any mechanism to check the session is online?

**Comment by Luzzotica** [comment]
Sessions should be deleted automatically on both ends when deleted.

If they are not, then I am not aware of any way to detect if a session is no longer valid.

Sorry I know that isn't helpful. 
If this is happening in trust wallet, then the issue is likely in their court: They might not have the most recent version of the WC repo, and so it isn't automatically deleting it on the dApp end.
