### ISSUE TITLE
Gas fee calculation wrong when value is greater than 0

### ISSUE THREAD

**Issue by samuel2629** [WalletConnect/WalletConnectFlutterV2#171]
When i send a transaction with a value of 0 (0x0) it is ok and fee calculation is ok, but when value is more than 0, gas fee is wrong and leading to an error "intrinsic gas too low".

In the example below is fee is equal to 0 it works well if it is equal to 0.01 for example it won't work.

```
Transaction transaction = Transaction.callContract(
          from: EthereumAddress.fromHex(wallet!),
          contract: contract,
          function: function,
          parameters: arg);

    launchUrl(Uri.parse("metamask://"), mode: LaunchMode.externalApplication);

    EthereumTransaction ethereumTransaction = EthereumTransaction(
        from: wallet,
        to: "0x9B2044615349Ffe31Cf979F16945D0c785eED7da",
        value: "0x${hasFee ? BigInt.from(fee! * 1e18).toRadixString(16) : "0"}",
        data: hex.encode(List<int>.from(transaction.data!)),
      );


    var transactionId = await connector.request(
      topic: sessionConnect!.session.topic,
      chainId: "eip155:5",
      request: SessionRequestParams(
          method: 'eth_sendTransaction',
          params: [ethereumTransaction.toJson()],
        ),
    );
```

**Comment by Luzzotica** [comment]
I don't know much about gas on ethereum, but I'm assuming you're getting an error back from the wallet saying the gas is too low?

It looks to me like you're requesting a value transfer of some EVM token and that the wallet is getting angry because you don't have enough gas.
This isn't a WalletConnect issue.
It sounds like the wallet is what is returning the error. Please take up the issue with whatever wallet is throwing the error back to you.
