### ISSUE TITLE
How to detect current network on MetaMask when send request

### ISSUE THREAD

**Issue by nqhhdev** [WalletConnect/WalletConnectFlutterV2#238]
**Describe the bug**
Basically I send a request with `chainId` of the Moonbeam network and open Metamask with current network Ethereum Mainnet.
After that nothing happened so I want to detect current network on MetaMask and I can switch other networks. 

**To Reproduce**
1. Send a request with `chainId` of the A network
```dart
Future<dynamic> sendTransaction(
      {required List<dynamic> params}) async {
    log('SpendingAndWalletStepperModel::sendTransaction()');
    try {
      final String encodedUri = Uri.encodeComponent('$_uri');

      await launchUrlString(
        'metamask://wc?uri=$encodedUri',
        mode: LaunchMode.externalApplication,
      );

      final signResponse = await _signClient!.request(
        topic: _sessionData!.first.topic,
        chainId: "eip155:1284", /// Moonbeam Network
        request: SessionRequestParams(
          method: 'eth_sendTransaction',
          params: params,
        ),
      );

      return signResponse;
    } catch (e) {
      log('SpendingAndWalletStepperModel::sendTransaction() - FAILED $e');
      rethrow;
    }
  }
```
2. Open MetaMask with current network  Ethereum Mainnet (`chainId: 1`)
3. Nothing happened 

**Expected behavior**
- Want to ecxactly current network on MetaMask
- If you send a `chainId` different from the current `chainId` on the MetaMask wallet, an error will be thrown that can be handled.

**WalletConnectFlutterV2 version**
- `walletconnect_flutter_v2: 2.1.11`

**Smartphone (please complete the following information):**
 - Device: Iphone 15 promax
 - OS: iOS
 - Dapp Metask v7.12.3 (1230)

**Additional context**

**Comment by nqhhdev** [comment]
Hi @Luzzotica, Thank you for your contributions to the WalletConnectFlutterV2 community, I have an issue like the one above, can you help me check it? 
Thanks

**Comment by mthinh** [comment]
This is also my concern, actually you can listen for events `accountChanged`, `chainChanged` to detect current selected chain id in wallet app,
The thing is if the event is not emitted (for some reasons) when you just started your app, you won't know which chain currently connected.

**Comment by nqhhdev** [comment]
Thanks @mthinh  to contributors and for discussing about issue
IMO: 
- If you listen for events `accountChanged ` and `chainChange` are not enough to handle other cases.
- In v1, we can handle errors when sending request with a different `chainId`. Why not in v2
- If we give the user switch a manual, it's just a workaround. In the long run, we can't do that

**Comment by quetool** [comment]
Hello! MetaMask it's a particular case cause it would approve only the chain you have currently selected on it. So, in order to understand which chain is that, you should check your session object after connecting it. Like for instance, I would listen to onSessionConnect event and do the following

```
void _onSessionConnect(SessionConnect? event) {
  debugPrint(jsonEncode(event?.session.toJson()));
  final namesSpaces = event!.session.namespaces.values.toList();
  final accounts =
      namesSpaces.map((e) => e.accounts).expand((a) => a).toList();
  final approvedChains = NamespaceUtils.getChainsFromAccounts(
    accounts,
  );
  debugPrint('approvedChains ${approvedChains.join(', ')}');
}
```

`NamespaceUtils.getChainsFromAccounts(accounts)` is a handy util method that allows to get the approved chains from the current accounts in session. So after that you should have your current MM chain inside `approvedChains`.

Now, if you are planning to send a transaction on a different chain than the approved one, you should first call `wallet_switchEthereumChain` or, probably better, `wallet_addEthereumChain` to switch MM to that chain. Upon success, you then call your `eth_sendTransaction` request.

**Comment by mthinh** [comment]
Thanks for your response @quetool , but I have tried to use `wallet_switchEthereumChain` by calling 
```
await _signClient!.request(
        topic: _sessionData!.first.topic,
        chainId: currentChainId,
        request: SessionRequestParams(
          method: 'wallet_switchEthereumChain',
          params: [ 
          {
           "chainId: "newChainId"
          }
          ],
        ),
      );
```
The thing is if we dont know the current selected chain in Metamask, there's nothing happen

**Comment by nqhhdev** [comment]
Hi @quetool  I have a question:
1. Can we call multiple methods at the same time?

```dart
Future<dynamic> sendTransaction(
      {required List<dynamic> params}) async {
    log('SpendingAndWalletStepperModel::sendTransaction()');
    try {
      final String encodedUri = Uri.encodeComponent('$_uri');

      await launchUrlString(
        'metamask://wc?uri=$encodedUri',
        mode: LaunchMode.externalApplication,
      );

    final signResponse = await _signClient!.request(
        topic: _sessionData!.first.topic,
        chainId: "eip155:1284", /// Moonbeam Network
        request: SessionRequestParams(
          method: 'wallet_switchEthereumChain',
          params: [{'chainId': 'eip155:1284'}],
        ),
      );

      final signResponse = await _signClient!.request(
        topic: _sessionData!.first.topic,
        chainId: "eip155:1284", /// Moonbeam Network
        request: SessionRequestParams(
          method: 'eth_sendTransaction',
          params: params,
        ),
      );

      return signResponse;
    } catch (e) {
      log('SpendingAndWalletStepperModel::sendTransaction() - FAILED $e');
      rethrow;
    }
  }
```

2. What happens when I call many methods continuously?

**Comment by quetool** [comment]
Hello @nqhhdev! As a matter of "can" yes you can, but I would advice no to do it. Since we are dealing with messages through a relay you don't know how much time could pass in between one request and the other. Furthermore, in this case you will need the response from `wallet_switchEthereumChain` to succeed before calling `eth_sendTransaction` otherwise you may be sending the second request to the wrong chain.

Side note: your chainId in switch method must be in hexadecimal, so in your case `params: [{'chainId': '0x504'}]`

**Comment by quetool** [comment]
BTW, regarding MetaMask issue, there's an ongoing opened issue in MetaMask repo that highlights this very issue. https://github.com/MetaMask/metamask-mobile/issues/6655

Basically MM is not updating the active network upon calling switch method. I'll close this for now! Thanks!
