### ISSUE TITLE
 after connected uniswap, chains list shows unsupported by your wallet

### ISSUE THREAD

**Issue by leeway1208** [WalletConnect/WalletConnectFlutterV2#291]
I have connected to uniswap. but I can not change the chain. It shows unsupported by your wallet
![image](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/8113938/2d837653-5b30-46cd-99ae-f52719595a80)

**Comment by quetool** [comment]
Hello @leeway1208! Thanks for the report! This seems to be an issue on Uniswap, allow me some time to investigate.

**Comment by leeway1208** [comment]
> Hello @leeway1208! Thanks for the report! This seems to be an issue on Uniswap, allow me some time to investigate.

Thx~~~

**Comment by quetool** [comment]
Hello @leeway1208! Could you try if the same is happening on Pancakeswap?

**Comment by leeway1208** [comment]
> Hello @leeway1208! Could you try if the same is happening on Pancakeswap?

Yes. Always shows requesting.
![image](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/8113938/0dd2295b-1a8e-4024-885f-82abc399a40b)

**Comment by quetool** [comment]
But the different chains are enabled, right?

**Comment by leeway1208** [comment]
> But the different chains are enabled, right?

Yes

**Comment by quetool** [comment]
Sounds good. So, the reason why PancakeSwap is showing "Requesting..." could be because you are trying to switch to an unsupported chain (switching from Ethereum to BNB and viceversa shouldn't be a problem). Are you testing trying this out with our Sample Wallet?

Regarding Uniswap issue I'm still looking into it.

**Comment by quetool** [comment]
Hello @leeway1208! We have found the issue and we notified Uniswap team! But we are also implementing a fix on our side just to overcome this issue in the future and avoid confusions. Thank you so mucho for your report! 🎉
I'll keep you posted once our fix is deployed!

**Comment by leeway1208** [comment]
Thanks~

**Comment by quetool** [comment]
Hello @leeway1208! Could you check again on Uniswap? Thanks!

**Comment by leeway1208** [comment]
> Hello @leeway1208! Could you check again on Uniswap? Thanks!

I can change the chain now. But list displays the text that approve in wallet. What should I do in next. Thanks
![image](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/8113938/18d19825-3e7d-4c95-8292-11e90e63bbcb)

**Comment by quetool** [comment]
Yeah so, the fix from Uniswap consist in enabling every chain **they** support but that doesn't mean **you** support it. Which is most probably the case here. So if you want to support Base (and every other chain listed there) you should add support on your side. Check how it's done in our sample wallet.

In the coming days another patch for the wagmi connector is going to be release that will enable oney the chains the wallet support and not every chain.

I'll close for now as this issue is fixed, but feel free to open a new issue if you encounter.
