### ISSUE TITLE
Trust Wallet auth fails

### ISSUE THREAD

**Issue by PramodJoshi** [WalletConnect/WalletConnectFlutterV2#88]
Authentication fails after signing auth request on Trust Wallet.

Chain: Polygon
Trust Wallet (Android): v7.21.1

```
flutter: Authentication failed: WalletConnectError(code: -1, message: Invalid signature, data: null)
```

**Comment by Luzzotica** [comment]
I believe this is a bug with Trust Wallet.

They are constructing and signing the incorrect message.

This is the message that Trust Wallet constructs:
![image](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/32227368/08e55e83-acde-4874-bc63-9956cea8c7e5)

But all the WalletConnect examples apps include 2 new lines instead of just the one that Trust Wallet seems to have.

The [EIP](https://eips.ethereum.org/EIPS/eip-4361) doesn't specify if the the new lines should disappear if there is no statement, so I am assuming that Trust Wallet is in the wrong here.

To resolve this issue simply add a statement to your auth request and it will work as intended.

**Comment by PramodJoshi** [comment]
That worked. Thanks!
