### ISSUE TITLE
Web3Wallet.approveSession does not provide a result

### ISSUE THREAD

**Issue by dmdeklerk** [WalletConnect/WalletConnectFlutterV2#99]
Sorry for spamming this issue as it has been discussed in various places (#94 among others) as I said in https://github.com/WalletConnect/WalletConnectFlutterV2/issues/94#issuecomment-1580653499 and @LvDj states correctly here https://github.com/WalletConnect/WalletConnectFlutterV2/issues/94#issuecomment-1572014458

We run into the situation where `Web3Wallet.approveSession` sometimes returns a response and sometimes it doesn't (60% of the time it does). 

On the DApp side the call to Web3Wallet.approveSession is successfully received and the session is established. Its just that on the wallet side Web3Wallet.approveSession simply times out.

We are trying to find out what is going on here exactly which is very difficult as sometimes it works and sometimes it doesnt.

Edit: that test I removed did not in fact establish the connection on the dapp side. Now that we are testing while removing all pairings on the dapp side the issue seems to have gone away.

Update: now that I have set various print statements in SignEngine.approveSession to see where it halts and try to connect continuously to see if it fails again. Now all of a sudden after weeks of running into this - the issue does not surface. I must say that i havent tried to connect so many consecutive times in a row. Perhaps there needs to be a delay before we run into this again.  - but print statements are set and I will update the second I see where the `Web3Wallet.approveSession` halts again.

**Comment by Luzzotica** [comment]
This has been my issue.

The moment I try to monitor it failing, it refuses to fail.

I appreciate the work you're putting in to help me figure it out.

I just added a logger to the repo to help me out. I haven't been able to ever get it to fail when running my tests locally, but it seems that running the tests in a github action have the failing (Though not the 40% that you guys all have).

Thank you again!

**Comment by iota9star** [comment]
@dmdeklerk I think before we actually identify the code issue, we can first use the latest code on the main branch to see if the problem still occurs now. Of course, I believe the key issue is with the WalletConnect mechanism, and it's not easy for us to wait on the wallet side because we don't know when the DApp will be ready. Fortunately, the `wc_sessionSettle` method is not a necessary condition, otherwise this would lead to endless waiting.

```yaml
dependency_overrides:
  walletconnect_flutter_v2:
    git:
      url: https://github.com/WalletConnect/WalletConnectFlutterV2.git
      ref: "cb0e59c"
```

I am providing the flowchart below to help understand this process.

![image](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/21272154/e84112c8-640e-4cb6-80eb-37cfee7f6f1c)

**Comment by Luzzotica** [comment]
I do not believe the flowchart you provided is accurate.

Reasoning:
The session proposal uses the Pairing Topic.
The session settle uses the Session Topic.

It's more likely that the session settle isn't even getting sent to the dapp because it hasn't yet subscribed to the session topic by the time it is received by the relay.
Though, thinking about that, I am not sure that would be the issue either because the relay is quite robust, and is designed to send cached messages once you subscribe (Otherwise you wouldn't be able to spin up a wallet and just see all of the requests there).

So I'm back to square one: I don't know what would cause the dapp to not receive the session settle request.

My honest guess is that it is receiving it, but it's getting discarded for some reason.

**Comment by Luzzotica** [comment]
Just pushed out 2.0.9, made some minor changes, I doubt it actually fixed it, but let me know.

Again, I'm literally unable to recreate this issue on my end xD

**Comment by dmdeklerk** [comment]
Hi @Luzzotica , quick update, our development focus has switched to a different part of the app stack which is why we havent ran into the reported issue. 
We expect to get to get back next week to running the Dapp and Iphone simulator side by side again which will allow us to see whats going on again.

**Comment by Luzzotica** [comment]
@dmdeklerk Thank you for the continued efforts on this.

If I see it pop up on my end I'll certainly put my findings here.

So far I have only had it happen with javascript/web apps. I haven't experienced it in a flutter-flutter environment.

**Comment by Luzzotica** [comment]
I haven't heard any additional issues on this in the past 30 days and I haven't experienced it, so I am going to close this issue.

**Comment by BrianCliton** [comment]
I encountered the same problem on version 2.1.4. It does not necessarily appear, but it occurs frequently. Sometimes there is no response when executing .approveSession. It will appear on both Android and iOS
